[package]
name = "token-bindings-test"
version = { workspace = true }
authors = [
    "Ethan Frey <ethanfrey@users.noreply.github.com>",
    "Jake Hartnell <jakehartnell@users.noreply.github.com>",
]
description = "Multitest (and other test helpers) support for Token factory contracts"

edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
default = []
backtrace = ["anyhow/backtrace"]
cosmwasm_1_1 = ["cosmwasm-std/cosmwasm_1_1", "cw-multi-test/cosmwasm_1_1"]
cosmwasm_1_2 = [
    "cosmwasm_1_1",
    "cosmwasm-std/cosmwasm_1_2",
    "cw-multi-test/cosmwasm_1_2",
]
cosmwasm_1_3 = [
    "cosmwasm_1_2",
    "cosmwasm-std/cosmwasm_1_3",
    "cw-multi-test/cosmwasm_1_3",
]
cosmwasm_1_4 = [
    "cosmwasm_1_3",
    "cosmwasm-std/cosmwasm_1_4",
    "cw-multi-test/cosmwasm_1_4",
]

[dependencies]
anyhow = { workspace = true }
cosmwasm-std = { workspace = true }
cw-multi-test = { workspace = true }
cw-storage-plus = { workspace = true }
itertools = { workspace = true }
token-bindings = { workspace = true, path = "../bindings" }
schemars = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
thiserror = { workspace = true }
